# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: dev - build and trigger Azure to retrieve

on:
   push:
     branches:
       - main
   workflow_dispatch:

jobs:
  restore-build-publish:
    runs-on: ubuntu-latest

    steps:  
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
          
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            Common:
            - 'Test2Webs/Common'
            External:
            - 'Test2Webs/External.Web'
            Internal:
            - 'Test2Webs/Internal.Web'       

      - name: Build Internal
        if: (steps.changes.outputs.Internal == 'true' || steps.changes.outputs.Common == 'true')
        run: dotnet build ./Test2Webs/Internal.Web/Internal.Web.csproj --configuration Release

      - name: Upload Internal Artifact
        if: (steps.changes.outputs.Internal == 'true' || steps.changes.outputs.Common == 'true')
        uses: actions/upload-artifact@v2
        with:
          name: Test2Webs-Internal
          path: ./Test2Webs/Internal.Web/bin/Release/net6.0/win-x64

      - uses: azure/pipelines@v1
        if: (steps.changes.outputs.Internal == 'true' || steps.changes.outputs.Common == 'true')      
        with:
          azure-devops-project-url: https://dev.azure.com/jessbrox809/Test2Webs
          azure-pipeline-name: Internal-Dev-Deploy
          azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}



      - name: Build External
        if: (steps.changes.outputs.External == 'true' || steps.changes.outputs.Common == 'true')
        run: dotnet build ./Test2Webs/External.Web/External.Web.csproj --configuration Release

      - name: Upload External Artifact
        if: (steps.changes.outputs.External == 'true' || steps.changes.outputs.Common == 'true')
        uses: actions/upload-artifact@v2
        with:
          name: Test2Webs-External
          path: ./Test2Webs/External.Web/bin/Release/net6.0/win-x64

      - uses: azure/pipelines@v1
        if: (steps.changes.outputs.External == 'true' || steps.changes.outputs.Common == 'true')      
        with:
          azure-devops-project-url: https://dev.azure.com/jessbrox809/Test2Webs
          azure-pipeline-name: External-Dev-Deploy
          azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}


