name: dev-external - build and trigger Azure to retrieve

on:
   push:
     branches:
       - main
     paths:
       - 'Test2Webs/Common/**'
       - 'Test2Webs/External.Web/**'
   workflow_dispatch:

jobs:
  restore-build-publish:
    runs-on: ubuntu-latest

    steps:  
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3   

      - name: Publish External
        run: dotnet publish ./Test2Webs/External.Web/External.Web.csproj --configuration Release

      - name: Upload External Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Test2Webs-External
          path: ./Test2Webs/External.Web/bin/Release/net6.0

      - uses: azure/pipelines@v1    
        with:
          azure-devops-project-url: https://dev.azure.com/jessbrox809/Test2Webs
          azure-pipeline-name: External-Dev-Deploy
          azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
