name: release-publish artifact and trigger Azure to retrieve

on:
   release:
     types: [created]
   workflow_dispatch:

jobs:
  restore-build-publish:
    runs-on: ubuntu-latest

    steps:  
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: octokit/request-action@v2.x
        id: get_last_2_releases
        with:
          url: https://api.github.com/repos/{owner}/{repo}/releases
          per_page: 5
          sort: created_at
          order: desc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: "echo previous release: '${{ steps.get_last_2_releases.outputs.data }}'"          
