name: release-publish artifact and trigger Azure to retrieve

on:
   release:
     types: [created]
   workflow_dispatch:

jobs:
  restore-build-publish:
    runs-on: ubuntu-latest

    steps:  
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get the 2nd release's tag name
        shell: bash
        run: |
          releases=$(octokit/request-action@v1 \
            with: \
              url: https://api.github.com/repos/{{ github.repository }}/releases \
              per_page: 2 \
              sort: created_at \
              order: desc)
          tag_name=$(jq -r '.[1].tag_name' releases)
          echo "{tag_name}={$tag_name}" >> $GITHUB_OUTPUT 
