name: release-publish artifact and trigger Azure to retrieve

on:
   release:
     types: [created]
   workflow_dispatch:

jobs:
  restore-build-publish:
    runs-on: ubuntu-latest

    steps:  
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: octokit/request-action@v2.x
        id: get_last_2_releases
        with:
         route: GET /repos/{owner}/{repo}/releases
         owner: JesseBroxterman
         repo: Test2Webs
         per_page: 2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Testing Data
        run: "echo Requested Data: '${{fromJson(steps.get_last_2_releases.outputs.data)}}'"
