name: release-publish artifact and trigger Azure to retrieve

on:
   release:
     types: [created]
   workflow_dispatch:

jobs:
  restore-build-publish:
    runs-on: ubuntu-latest

    steps:  
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: octokit/request-action@v2.x
        id: get_last_2_releases
        with:
         route: GET /repos/{owner}/{repo}/releases
         owner: JesseBroxterman
         repo: Test2Webs
         per_page: 2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Convert Release Array
        id: conversion
        run: |
          last_2_releases=$(jq -r '.[0]' ${{ steps.get_last_2_releases.outputs.data }})
          last_2_releases=last_2_releases >> $GITHUB_OUTPUT
      
      - run: "echo previous release: '${{steps.conversion.outputs.last_2_releases}}'"

      - shell: bash
        run: |
          tag_name=$(jq -r '.[1].tag_name' ${{steps.conversion.outputs.last_2_releases}})
          echo "The second release's tag name is: $tag_name"


