name: release-publish artifact and trigger Azure to retrieve

on:
   release:
     types: [created]
   workflow_dispatch:

jobs:
  restore-build-publish:
    runs-on: ubuntu-latest

    steps:  
      - name: View the github context
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      - uses: octokit/graphql-action@v2.x
        id: get_latest_release
        with:
          query: |
            query release($owner:String!,$repo:String!) {
              repository(owner:$owner,name:$repo) {
                releases(first:2) {
                  nodes {
                    tagName
                  }
                }
              }
            }
          variables: |
            owner: JesseBroxterman
            repo: Test2Webs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - run: "echo 'latest release: ${{ steps.get_latest_release.outputs.data }}'"

      - name: Get tag name of second release
        run: |
          data = ${{ steps.get_last_2_releases.outputs.data }}
          # second_release_tag_name = data.repository.releases.nodes[1].tagName
          # echo second_release: "${second_release_tag_name}"
